server:
  port: 9092

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017
      host: localhost
      port: 27017
      username: root
      password: example
      database: UserProfileDB
  redis:
      host: localhost
      port: 6379
